services:
  admintools:
    container_name: admintools
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    restart: always
    volumes:
      - /Users/jmcombs/Projects/dockerTools/files:/home/coder/files
